package template

const NotEditMark = `
// Code generated by github.com/soedomoto/db2gorm/gen. DO NOT EDIT.
`

const Header = NotEditMark + `
package {{.Package}}

import(	
	{{range .ImportPkgPaths}}` + "\"" + `{{.}}` + "\"\n" + `{{end}}
)
`
